# Generated by Django 4.2.7 on 2025-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1023)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('PER', 'Peripherals'), ('COM', 'Components'), ('ACC', 'Accessories')], default='COM', max_length=3)),
            ],
        ),
    ]
