# Generated by Django 4.2.7 on 2025-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Peripheral', 'Per'), ('Component', 'Com'), ('Accessorie', 'Acc')], default='Component', max_length=20),
        ),
    ]
