# Generated by Django 4.2.7 on 2025-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Peripheral', 'Peripheral'), ('Component', 'Component'), ('Accessorie', 'Accessorie')], default='Component', max_length=20),
        ),
    ]
